### PR TITLE
add bower support

### PR DESCRIPTION
**Pull request by grounded042**

### CODE REVIEW

**Comment by potomak** [comment]
Thanks for this PR. Please fix indentation (`ignore` and `dependencies`) and I will merge it.

Please fix also dependency as suggested by @pburtchaell

**Comment by grounded042** [comment]
@potomak sorry for the wait. I believe I have fixed the indentation and I set the jQuery version number.

**Comment by grounded042** [comment]
The indentation might look a little weird, but I followed the bower indentation rules: 1 tab = 2 spaces.

**Comment by potomak** [comment]
@grounded042 the indentation is wrong, see https://raw.github.com/grounded042/jquery-instagram/master/bower.json

**Comment by grounded042** [comment]
@potomak Not sure what happened. Looked fine on my local box. I'll take a look tonight and push again. Sorry about this.

**Comment by potomak** [comment]
@grounded042 no worries! You're only a couple of commits away from the merge of this PR.

**Comment by grounded042** [comment]
@potomak it should be good to go now

**Comment by potomak** [comment]
@grounded042 it looks ok except for the jquery dependency, jquery-instagram works also with jquery v. 1, what do you think to change dependency version to `"jquery": ">= 1.9.0"`?

**Comment by grounded042** [comment]
@potomak is there documentation on Bower supporting that? I can't seem to find good documentation on that. If it does support that, I'm all for it.

**Comment by pburtchaell** [comment]
I have never seen `*` used — I have however seen latest. My suggestion would be the register test both and see which works. 

If we can't find a solution, perhaps using the current version of all dependencies/last tested version would work.

**Comment by potomak** [comment]
@grounded042 at http://bower.io/#defining-a-package

> `version`: A semantic version number (see semver).

Reference about semver parsing package: https://github.com/isaacs/node-semver/

**Comment by grounded042** [comment]
@potomak should be all good to go now.

**Comment by potomak** [comment]
@grounded042 perfect, squash commits and I'll merge!

**Comment by pburtchaell** [comment]
FYI I asked one of the core team members for Bower which is correct: "latest" or "*". Both work the same and are accepted in all versions of Bower. It is a personal preference which you use.

**Comment by potomak** [comment]
@pburtchaell thanks for pointing it out.

**Comment by grounded042** [comment]
@potomak squash complete!

**Comment by potomak** [comment]
@grounded042 thanks!

**Pull request merged**
